# Generated by Django 5.0.7 on 2025-03-31 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cart_cartitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='is_paud',
            new_name='is_paid',
        ),
    ]
