# Generated by Django 5.0.7 on 2025-03-31 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_color_varient_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColorVarient',
            new_name='ColorVariant',
        ),
        migrations.RenameModel(
            old_name='SizeVarient',
            new_name='SizeVariant',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='color_varient',
            new_name='color_variant',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size_Varient',
            new_name='size_variant',
        ),
    ]
